--
-- PostgreSQL database dump
--

-- Dumped from database version 14.2
-- Dumped by pg_dump version 14.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: dev
--

INSERT INTO public.categories (id, name, description, created_at) VALUES (1, 'Action', 'Traditionally (but no longer exclusively) aimed at male readers, features physical action and violence, usually around a quest or mission set in exotic locations such as deserts, jungles, or mountains. Stories often include elements of technology, weapons, and other hardware. The genre is still largely aimed towards males (for example, the James Bond series is often categorized as action), but many later works feature women in roles more traditionally reserved for males, such as heroic bodyguards.', '2022-05-27 05:24:33.190129');
INSERT INTO public.categories (id, name, description, created_at) VALUES (2, 'Adventure', 'Books whose characters undergo some kind of quest or task to accomplish a goal, often a journey, and usually dangerous.', '2022-05-27 05:24:33.201024');
INSERT INTO public.categories (id, name, description, created_at) VALUES (3, 'Alternate History', 'Discussion of what might have been, given different decisions and actions at key points in history -- if Hitler had won WWII, or if Hitler hadn''t ever come to power, for example.', '2022-05-27 05:24:33.206509');
INSERT INTO public.categories (id, name, description, created_at) VALUES (4, 'Animal', 'Books which have animals as the main characters, or whose plots revolve around animals. For example, the Redwall series by Brian Jacques.', '2022-05-27 05:24:33.211923');
INSERT INTO public.categories (id, name, description, created_at) VALUES (5, 'Artificial Intelligence', 'Stories in which the main story, a major sub-theme, or one (or more) of the central characters, involves or explores the role and/or nature of computer intelligence. Examples: 2001 (HAL), Number of the Beast (Gay Deceiver), etc.', '2022-05-27 05:24:33.216828');
INSERT INTO public.categories (id, name, description, created_at) VALUES (6, 'Biographical', 'Nonfiction books about the lives of real people.', '2022-05-27 05:24:33.220912');
INSERT INTO public.categories (id, name, description, created_at) VALUES (7, 'Children', 'Books intended either to be read to children, or to be read by children who are still learning to read well, up to perhaps age 8 or so.', '2022-05-27 05:24:33.225098');
INSERT INTO public.categories (id, name, description, created_at) VALUES (8, 'Christmas', 'Works about the traditional Christian holy day.', '2022-05-27 05:24:33.229075');
INSERT INTO public.categories (id, name, description, created_at) VALUES (9, 'Classic', 'Books that are recognizable by a typical high-school grad, whether they''ve read them or not. Examples include War & Peace, Great Expectations, Of Mice & Men, The Pearl.', '2022-05-27 05:24:33.23325');
INSERT INTO public.categories (id, name, description, created_at) VALUES (10, 'Coming of Age', 'Works that have an emphasis on the journey from youth to adulthood.', '2022-05-27 05:24:33.238033');
INSERT INTO public.categories (id, name, description, created_at) VALUES (11, 'Computers', 'Books about computer software packages, computer hardware, computer languages and operating systems, various computer applications, the internet, and stories about same.', '2022-05-27 05:24:33.243716');
INSERT INTO public.categories (id, name, description, created_at) VALUES (12, 'Contemporary', 'The setting is in the modern world, filled with the hustle and bustle of our everyday lives.', '2022-05-27 05:24:33.24906');
INSERT INTO public.categories (id, name, description, created_at) VALUES (13, 'Decision Tree', 'Includes those "Choose Your Own Adventure" books you may remember. The reader chooses which parts of the book to read to form a story based on the decisions they make for the characters.', '2022-05-27 05:24:33.254831');
INSERT INTO public.categories (id, name, description, created_at) VALUES (14, 'Epic Saga', 'A book, or often series of books, with far-reaching storylines that involve an entire region or world (or more). Usually, characters in such sagas have great effect on their surroundings. The books or series themselves tend to be long, and often dense reading.', '2022-05-27 05:24:33.260722');
INSERT INTO public.categories (id, name, description, created_at) VALUES (15, 'Erotic', 'Stories in which sex and/or sensuality play a major role. Not necessarily romance, as love is not always included. Often for mature audiences only.', '2022-05-27 05:24:33.266198');
INSERT INTO public.categories (id, name, description, created_at) VALUES (16, 'Fairy Tales', 'Books which deal heavily with well-known children''s wonder tales such as Cinderella, Snow White, etc. Also includes stories which feature fairies, faeries, and fae as primary characters or plot devices.', '2022-05-27 05:24:33.271435');
INSERT INTO public.categories (id, name, description, created_at) VALUES (17, 'Family Life', 'Best described by Plato in ''The Republic" --- We have been long expecting that you would tell us something about the family life of your citizens--how they will bring children into the world, and rear them when they have arrived, and, in general, what is the nature of this community of women and children-for we are of opinion that the right or wrong management of such matters will have a great and paramount influence on the State for good or for evil.', '2022-05-27 05:24:33.276686');
INSERT INTO public.categories (id, name, description, created_at) VALUES (18, 'Fantasy', 'Speculative fiction that relies on magic and/or mythology for its differences from "reality."', '2022-05-27 05:24:33.281852');
INSERT INTO public.categories (id, name, description, created_at) VALUES (19, 'Film', 'Books pertaining to the Film and Television entertainment industry. Works may include history of the medium, commentary, textbooks, episode guides, collectibles, trivia, movie storybooks and related published film tie-ins. Not to be confused with the "Novelizations" genre, which involves adaptations of stories from these media into novel form, rather than the reverse.', '2022-05-27 05:24:33.286991');
INSERT INTO public.categories (id, name, description, created_at) VALUES (20, 'Fine Arts', 'Books in which the primary focus involves one (or more) branches of the visual or performing arts: Drawing & Painting, Photography, Sculpture, Fashion, Opera, Concert Pianist, Violinist etc.', '2022-05-27 05:24:33.291997');
INSERT INTO public.categories (id, name, description, created_at) VALUES (21, 'Food', 'Books in which the primary focus involves food and/or beverages. Includes (variously) cookbooks, tell alls & (auto)biographies by people in the industry, restaurant reviews & guides, ingredient and technique guides, books on making & appreciating various beverages (alcoholic or otherwise), etc.', '2022-05-27 05:24:33.297125');
INSERT INTO public.categories (id, name, description, created_at) VALUES (22, 'Games', 'Books intended to provide or enhance rules for game-playing, often role-playing games such as Dungeons & Dragons.', '2022-05-27 05:24:33.302333');
INSERT INTO public.categories (id, name, description, created_at) VALUES (23, 'Genealogy', 'Books whose primary subject matter involves the exploration/documentation of family trees and family history.', '2022-05-27 05:24:33.307274');
INSERT INTO public.categories (id, name, description, created_at) VALUES (24, 'Ghosts', 'Stories that involve the restless non-corporeal spirits of former mortals. Usually, but not always, a sub-genre under horror.', '2022-05-27 05:24:33.312195');
INSERT INTO public.categories (id, name, description, created_at) VALUES (25, 'Graphic Novel', 'A novel whose narrative is related through a combination of text and art, often in western style comic-strip form. Includes many superhero works, such as Superman and X-men.', '2022-05-27 05:24:33.317763');
INSERT INTO public.categories (id, name, description, created_at) VALUES (26, 'Hi-Tech', 'Tales in which technology is a major focus -- whether as a goal, a tool, a weapon, or something else. Often, but not always, science fiction.', '2022-05-27 05:24:33.323203');
INSERT INTO public.categories (id, name, description, created_at) VALUES (27, 'Historical', 'Stories that take place in the past. Usually the plots are things that could actually have happened and are sometimes based on true events.', '2022-05-27 05:24:33.328502');
INSERT INTO public.categories (id, name, description, created_at) VALUES (28, 'Horror', 'Stories which intend to frighten the reader, whether with monsters (Frankenstein, Stephen King''s It), psychological terrors (much of V.C. Andrews'' work) or other methods.', '2022-05-27 05:24:33.333591');
INSERT INTO public.categories (id, name, description, created_at) VALUES (29, 'Juvenile', 'Books intended for those who are young (or young-at-heart) but no longer exactly children. Between the ages of 6 and 12. These are the first chapter books, like Little House on the Prairie and The Black Stallion. These deal with issues that kids between the ages of 6-12 deal with--friends, school, family relationships, etc. There is generally no sexual content at all in these books, and the violence is usually minimal--and not developed with detail if it is there.', '2022-05-27 05:24:33.338666');
INSERT INTO public.categories (id, name, description, created_at) VALUES (30, 'Martial Arts', 'Books in which the primary focus involves the martial arts and/or martial artists.', '2022-05-27 05:24:33.343836');
INSERT INTO public.categories (id, name, description, created_at) VALUES (31, 'Mathematics', 'Non-Fiction or fiction where the plot deals HEAVILY with mathematics in a central fashion.', '2022-05-27 05:24:33.349498');
INSERT INTO public.categories (id, name, description, created_at) VALUES (32, 'Mature', 'Books that, for reasons usually of sexual or violent content or themes requiring more experience to interpret, would usually be deemed appropriate for adults only. [But not specifically erotic]', '2022-05-27 05:24:33.35473');
INSERT INTO public.categories (id, name, description, created_at) VALUES (33, 'Medical', 'Books that use current or past medical science or themes as a basis. May include memoirs, textbooks, reference books, real life historical accounts, past and present medical research, etc.', '2022-05-27 05:24:33.359745');
INSERT INTO public.categories (id, name, description, created_at) VALUES (34, 'Mystery', 'Books about the solving of a particular crime, generally a murder, or other large crime.', '2022-05-27 05:24:33.365008');
INSERT INTO public.categories (id, name, description, created_at) VALUES (35, 'Nanotechnology', 'Stories involving microscopic machines.', '2022-05-27 05:24:33.370162');
INSERT INTO public.categories (id, name, description, created_at) VALUES (36, 'Philosophy', 'Works that represent attempts to understand the "greater truths" or humanity -- why are we here? what is good, and what is evil? -- through analysis rather than through speculation.', '2022-05-27 05:24:33.37586');
INSERT INTO public.categories (id, name, description, created_at) VALUES (37, 'Poetry', 'Books in which the primary focus is on the beauty of the written word, in all it''s varied splendors', '2022-05-27 05:24:33.381088');
INSERT INTO public.categories (id, name, description, created_at) VALUES (38, 'Politics', 'Books in which the primary focus involves politicians, the political process in general, major political incidents, political commentary, etc.', '2022-05-27 05:24:33.38918');
INSERT INTO public.categories (id, name, description, created_at) VALUES (39, 'Religion', 'Books that have as a focus or strong base one or more of the world''s major religions. May be non-fiction accounts and interpretations of the religion(s), or fiction that relies on an understanding of them.', '2022-05-27 05:24:33.394366');
INSERT INTO public.categories (id, name, description, created_at) VALUES (40, 'Romance', 'The trials, tribulations and triumphs of falling in love. Always has a happy ending, but not necessarily marriage.', '2022-05-27 05:24:33.399656');
INSERT INTO public.categories (id, name, description, created_at) VALUES (41, 'Science', 'Books that discuss current or past scientific advances, theories, and practices.', '2022-05-27 05:24:33.404638');
INSERT INTO public.categories (id, name, description, created_at) VALUES (42, 'Science Fiction', 'Fiction that relies on advanced technology and/or an expanded definition of current laws of science for its differences from regular fiction. Some people use the alternate term "Speculative Fiction" which poses fictional "what if" circumstances, and then explores {read: speculates} about the ramifications of those hypothetical circumstances. Those adhering to the latter usage sometimes consider "Science Fiction" (aka ''SciFi") to be a sub-genre of ''SpecFi'' with more of a ''hard science'' bent. At the present time, we use the terms interchangeably.', '2022-05-27 05:24:33.409733');
INSERT INTO public.categories (id, name, description, created_at) VALUES (43, 'Sport', 'Non-fiction books about real-world sporting events, games, and figures, or fiction in which the world of sports plays a heavy role.', '2022-05-27 05:24:33.414898');
INSERT INTO public.categories (id, name, description, created_at) VALUES (44, 'Supernatural', 'A "catchall" genre for supernatural activity. May include topics also contained in other genres eg Vampires. Also contains such paranormal activity as Psi powers. Unless some other supernatural element is involved (eg Psi Powers) should not be used purely if there are ET elements.', '2022-05-27 05:24:33.420036');
INSERT INTO public.categories (id, name, description, created_at) VALUES (45, 'Suspense', 'A grittier, more stressful, and more complex form of mystery, often with multiple crimes and a larger number of people affected, and emotional ambience taking precedence over logic and reason. Here, it''s not just about solving a puzzle or crime ... in fact, the protagonist might even be on the run from the antagonist, rather than the other way around.', '2022-05-27 05:24:33.425168');
INSERT INTO public.categories (id, name, description, created_at) VALUES (46, 'Theatrical', 'Stories in the form of dramatic plays or screenplays. May also include books which feature the world of theatre as a main focus.', '2022-05-27 05:24:33.430251');
INSERT INTO public.categories (id, name, description, created_at) VALUES (47, 'Thriller', 'Tough, resourceful, but usually ordinary ''heroes'' are pitted against the baddest of the bad, who are determined to destroy them, their country, or the entire world. High stakes, non-stop action, plot twists, exotic settings, and an intense pace until the adrenaline packed climax are found throughout these books. The plot of a thriller is usually driven by the villain, who presents obstacles that the hero must overcome.', '2022-05-27 05:24:33.435385');
INSERT INTO public.categories (id, name, description, created_at) VALUES (48, 'Time Travel', 'Books, often science fiction, which include and focus on travel through time, be it to the past or farther into the future than the normal passage of time allows.', '2022-05-27 05:24:33.440696');
INSERT INTO public.categories (id, name, description, created_at) VALUES (49, 'Vampire', 'Stories which feature vampires -- blood-drinking creatures of the night, typically -- as major themes or characters. The vampire(s) in question may be heroes or villains, or both! The cause of the vampirism could be an undead or magical curse (Dracula), a virus (Underworld), or genetic mutation (Blade). Often, but not always, a sub-genre under horror.', '2022-05-27 05:24:33.445727');
INSERT INTO public.categories (id, name, description, created_at) VALUES (50, 'Virtual Reality', 'Books which employ a world of computers that is separate from ours, but emulate it in some way. Typically science fiction, although there may be cases where our current technology approaches virtual reality, as well.', '2022-05-27 05:24:33.450827');
INSERT INTO public.categories (id, name, description, created_at) VALUES (51, 'War', 'Books that discuss and analyze factual wars, or the theories behind the same, or books that focus on events and figures during fictional military engagements.', '2022-05-27 05:24:33.455673');
INSERT INTO public.categories (id, name, description, created_at) VALUES (52, 'Western', 'Stories set in America''s "Old West," a time of cowboys, indians, frontier living, and shootouts with the sheriff or marshal.', '2022-05-27 05:24:33.460891');
INSERT INTO public.categories (id, name, description, created_at) VALUES (53, 'Young Adult', 'Books for the adolescent reader, i.e., between the ages of 12 and 18. These deal with the more serious issues faced by kids in their teens--they are significantly more raw--sexual content (though not containing, usually, the heavy "heaving bosom, masculine ,...uh...love muscle" descriptors. These books contain issues like teen pregnancy, dating violence, parental abuse, horror lite, and general "life experiences" that are common to the adolescent.', '2022-05-27 05:24:33.465903');


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dev
--

SELECT pg_catalog.setval('public.categories_id_seq', 53, true);


--
-- PostgreSQL database dump complete
--

