// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: book.sql

package db

import (
	"context"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (
    title,
    author,
    description,
    year,
    language,
    publisher,
    pages
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, title, author, description, year, language, publisher, pages, cover_url, created_at
`

type CreateBookParams struct {
	Title       string `json:"title"`
	Author      string `json:"author"`
	Description string `json:"description"`
	Year        int16  `json:"year"`
	Language    string `json:"language"`
	Publisher   string `json:"publisher"`
	Pages       int16  `json:"pages"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.Title,
		arg.Author,
		arg.Description,
		arg.Year,
		arg.Language,
		arg.Publisher,
		arg.Pages,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.Year,
		&i.Language,
		&i.Publisher,
		&i.Pages,
		&i.CoverUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getBook = `-- name: GetBook :one
SELECT id, title, author, description, year, language, publisher, pages, cover_url, created_at, categories, comment_count, bookmark_count, rate_count, rate_sum, rate_1, rate_2, rate_3, rate_4, rate_5, rate_6, rate_7, rate_8, rate_9, rate_10
FROM book_detail
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBook(ctx context.Context, id int32) (BookDetail, error) {
	row := q.db.QueryRowContext(ctx, getBook, id)
	var i BookDetail
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.Year,
		&i.Language,
		&i.Publisher,
		&i.Pages,
		&i.CoverUrl,
		&i.CreatedAt,
		&i.Categories,
		&i.CommentCount,
		&i.BookmarkCount,
		&i.RateCount,
		&i.RateSum,
		&i.Rate1,
		&i.Rate2,
		&i.Rate3,
		&i.Rate4,
		&i.Rate5,
		&i.Rate6,
		&i.Rate7,
		&i.Rate8,
		&i.Rate9,
		&i.Rate10,
	)
	return i, err
}

const getBookBrief = `-- name: GetBookBrief :one
SELECT id, title, author, publisher, cover_url, categories, comment_count, bookmark_count, rate_count, rate_sum
FROM book_detail
WHERE id = $1 LIMIT 1
`

type GetBookBriefRow struct {
	ID            int32  `json:"id"`
	Title         string `json:"title"`
	Author        string `json:"author"`
	Publisher     string `json:"publisher"`
	CoverUrl      string `json:"cover_url"`
	Categories    string `json:"categories"`
	CommentCount  int64  `json:"comment_count"`
	BookmarkCount int64  `json:"bookmark_count"`
	RateCount     int64  `json:"rate_count"`
	RateSum       int64  `json:"rate_sum"`
}

func (q *Queries) GetBookBrief(ctx context.Context, id int32) (GetBookBriefRow, error) {
	row := q.db.QueryRowContext(ctx, getBookBrief, id)
	var i GetBookBriefRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Publisher,
		&i.CoverUrl,
		&i.Categories,
		&i.CommentCount,
		&i.BookmarkCount,
		&i.RateCount,
		&i.RateSum,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, author, publisher, cover_url, categories, comment_count, bookmark_count, rate_count, rate_sum
FROM book_detail
WHERE NOT id > $2
ORDER BY id DESC
LIMIT $1
`

type ListBooksParams struct {
	Limit  int32 `json:"limit"`
	LastID int32 `json:"last_id"`
}

type ListBooksRow struct {
	ID            int32  `json:"id"`
	Title         string `json:"title"`
	Author        string `json:"author"`
	Publisher     string `json:"publisher"`
	CoverUrl      string `json:"cover_url"`
	Categories    string `json:"categories"`
	CommentCount  int64  `json:"comment_count"`
	BookmarkCount int64  `json:"bookmark_count"`
	RateCount     int64  `json:"rate_count"`
	RateSum       int64  `json:"rate_sum"`
}

func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]ListBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, listBooks, arg.Limit, arg.LastID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBooksRow{}
	for rows.Next() {
		var i ListBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Publisher,
			&i.CoverUrl,
			&i.Categories,
			&i.CommentCount,
			&i.BookmarkCount,
			&i.RateCount,
			&i.RateSum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
