// Code generated by sqlc. DO NOT EDIT.
// source: book_category.sql

package db

import (
	"context"
)

const createBookCategory = `-- name: CreateBookCategory :one
INSERT INTO book_category (
    book_id,
    category_id
) VALUES (
    $1, $2
) RETURNING book_id, category_id, created_at
`

type CreateBookCategoryParams struct {
	BookID     int32
	CategoryID int32
}

func (q *Queries) CreateBookCategory(ctx context.Context, arg CreateBookCategoryParams) (BookCategory, error) {
	row := q.db.QueryRowContext(ctx, createBookCategory, arg.BookID, arg.CategoryID)
	var i BookCategory
	err := row.Scan(&i.BookID, &i.CategoryID, &i.CreatedAt)
	return i, err
}

const deleteBookCategory = `-- name: DeleteBookCategory :exec
DELETE FROM book_category
WHERE book_id = $1 AND category_id = $2
`

type DeleteBookCategoryParams struct {
	BookID     int32
	CategoryID int32
}

func (q *Queries) DeleteBookCategory(ctx context.Context, arg DeleteBookCategoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteBookCategory, arg.BookID, arg.CategoryID)
	return err
}
