// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: book_category.sql

package db

import (
	"context"
)

const createBookCategory = `-- name: CreateBookCategory :one
INSERT INTO book_category (
    book_id,
    category_id
) VALUES (
    $1, $2
) RETURNING book_id, category_id, created_at
`

type CreateBookCategoryParams struct {
	BookID     int32 `json:"book_id"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) CreateBookCategory(ctx context.Context, arg CreateBookCategoryParams) (BookCategory, error) {
	row := q.db.QueryRowContext(ctx, createBookCategory, arg.BookID, arg.CategoryID)
	var i BookCategory
	err := row.Scan(&i.BookID, &i.CategoryID, &i.CreatedAt)
	return i, err
}
