// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: comment.sql

package db

import (
	"context"
	"time"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
    content,
    book_id,
    created_by
) VALUES (
    $1, $2, $3
) RETURNING id, content, book_id, created_by, created_at
`

type CreateCommentParams struct {
	Content   string `json:"content"`
	BookID    int32  `json:"book_id"`
	CreatedBy int32  `json:"created_by"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.Content, arg.BookID, arg.CreatedBy)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.BookID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, content, book_id, created_by, created_at
FROM comments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetComment(ctx context.Context, id int32) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.BookID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listCommentsByAccountId = `-- name: ListCommentsByAccountId :many
SELECT comments.id, comments.content, comments.book_id, comments.created_by, comments.created_at,
    b.title,
    b.cover_url
FROM comments
    JOIN books b on b.id = comments.book_id
WHERE created_by = $1 AND NOT comments.id > $2
ORDER BY comments.id DESC
LIMIT $3
`

type ListCommentsByAccountIdParams struct {
	UserID   int32 `json:"user_id"`
	LastID   int32 `json:"last_id"`
	PageSize int32 `json:"page_size"`
}

type ListCommentsByAccountIdRow struct {
	ID        int32     `json:"id"`
	Content   string    `json:"content"`
	BookID    int32     `json:"book_id"`
	CreatedBy int32     `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	Title     string    `json:"title"`
	CoverUrl  string    `json:"cover_url"`
}

func (q *Queries) ListCommentsByAccountId(ctx context.Context, arg ListCommentsByAccountIdParams) ([]ListCommentsByAccountIdRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByAccountId, arg.UserID, arg.LastID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByAccountIdRow{}
	for rows.Next() {
		var i ListCommentsByAccountIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.BookID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Title,
			&i.CoverUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByBookId = `-- name: ListCommentsByBookId :many
SELECT comments.id, comments.content, comments.book_id, comments.created_by, comments.created_at,
    COALESCE(a.name, '')        as username,
    COALESCE(a.avatar_url, '')  as avatar_url,
    COALESCE(a.is_admin, false) as is_admin
FROM comments
    LEFT JOIN accounts a
        ON a.id = comments.created_by
WHERE book_id = $1 AND NOT comments.id > $2
ORDER BY comments.id DESC
LIMIT $3
`

type ListCommentsByBookIdParams struct {
	BookID   int32 `json:"book_id"`
	LastID   int32 `json:"last_id"`
	PageSize int32 `json:"page_size"`
}

type ListCommentsByBookIdRow struct {
	ID        int32     `json:"id"`
	Content   string    `json:"content"`
	BookID    int32     `json:"book_id"`
	CreatedBy int32     `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	Username  string    `json:"username"`
	AvatarUrl string    `json:"avatar_url"`
	IsAdmin   bool      `json:"is_admin"`
}

func (q *Queries) ListCommentsByBookId(ctx context.Context, arg ListCommentsByBookIdParams) ([]ListCommentsByBookIdRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByBookId, arg.BookID, arg.LastID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByBookIdRow{}
	for rows.Next() {
		var i ListCommentsByBookIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.BookID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Username,
			&i.AvatarUrl,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET content = $2
WHERE id = $1
RETURNING id, content, book_id, created_by, created_at
`

type UpdateCommentParams struct {
	ID      int32  `json:"id"`
	Content string `json:"content"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, updateComment, arg.ID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.BookID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
