// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"fmt"
)

type AccountRoles string

const (
	AccountRolesAdmin AccountRoles = "admin"
	AccountRolesUser  AccountRoles = "user"
)

func (e *AccountRoles) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountRoles(s)
	case string:
		*e = AccountRoles(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountRoles: %T", src)
	}
	return nil
}

type FeedbackStatus string

const (
	FeedbackStatusProcessing  FeedbackStatus = "processing"
	FeedbackStatusResolved    FeedbackStatus = "resolved"
	FeedbackStatusNotResolved FeedbackStatus = "not_resolved"
)

func (e *FeedbackStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FeedbackStatus(s)
	case string:
		*e = FeedbackStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FeedbackStatus: %T", src)
	}
	return nil
}

type Account struct {
	ID          int64
	Username    string
	Email       string
	AvatarUri   sql.NullString
	Role        AccountRoles
	ModifiedAt  sql.NullTime
	CreatedAt   sql.NullTime
	EncodedHash string
}

type Book struct {
	ID          int32
	Title       string
	Author      string
	Description string
	ModifiedAt  sql.NullTime
	CreatedAt   sql.NullTime
}

type BookCategory struct {
	BookID     int32
	CategoryID int32
	CreatedAt  sql.NullTime
}

type Bookmark struct {
	ID        int64
	BookID    int32
	AccountID int64
	CreatedAt sql.NullTime
}

type Category struct {
	ID          int32
	Name        string
	Description sql.NullString
	ModifiedAt  sql.NullTime
	CreatedAt   sql.NullTime
}

type Comment struct {
	ID         int64
	Content    string
	BookID     int32
	CreatedBy  int64
	ModifiedAt sql.NullTime
	CreatedAt  sql.NullTime
}

type Feedback struct {
	ID         int64
	Content    string
	CreatedBy  int64
	Message    sql.NullString
	Status     FeedbackStatus
	ModifiedAt sql.NullTime
	CreatedAt  sql.NullTime
}

type Rate struct {
	ID         int64
	BookID     int32
	AccountID  int64
	ModifiedAt sql.NullTime
	CreatedAt  sql.NullTime
}
