// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Account struct {
	ID          int32
	Username    string
	Email       string
	EncodedHash string
	AvatarUri   sql.NullString
	IsAdmin     bool
	ModifiedAt  sql.NullTime
	CreatedAt   sql.NullTime
}

type Book struct {
	ID          int32
	Title       string
	Author      string
	Description string
	ModifiedAt  sql.NullTime
	CreatedAt   sql.NullTime
}

type BookCategory struct {
	BookID     int32
	CategoryID int32
	CreatedAt  sql.NullTime
}

type Bookmark struct {
	ID        int32
	BookID    int32
	CreatedBy int32
	CreatedAt sql.NullTime
}

type Category struct {
	ID          int32
	Name        string
	Description sql.NullString
	ModifiedAt  sql.NullTime
	CreatedAt   sql.NullTime
}

type Comment struct {
	ID         int32
	Content    string
	BookID     int32
	CreatedBy  int32
	ModifiedAt sql.NullTime
	CreatedAt  sql.NullTime
}

type Feedback struct {
	ID           int32
	Content      string
	CreatedBy    int32
	IsViewed     bool
	IsProcessing bool
	IsResolved   bool
	Message      sql.NullString
	ModifiedAt   sql.NullTime
	CreatedAt    sql.NullTime
}

type Rate struct {
	ID         int32
	BookID     int32
	CreatedBy  int32
	RateValue  int32
	ModifiedAt sql.NullTime
	CreatedAt  sql.NullTime
}
