// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"time"
)

type Account struct {
	ID             int32     `json:"id"`
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	AvatarUrl      string    `json:"avatar_url"`
	IsAdmin        bool      `json:"is_admin"`
	CreatedAt      time.Time `json:"created_at"`
}

type Book struct {
	ID          int32     `json:"id"`
	Title       string    `json:"title"`
	Author      string    `json:"author"`
	Description string    `json:"description"`
	Year        int16     `json:"year"`
	Language    string    `json:"language"`
	Publisher   string    `json:"publisher"`
	Pages       int16     `json:"pages"`
	CoverUrl    string    `json:"cover_url"`
	CreatedAt   time.Time `json:"created_at"`
}

type BookCategory struct {
	BookID     int32     `json:"book_id"`
	CategoryID int32     `json:"category_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type BookDetail struct {
	ID            int32     `json:"id"`
	Title         string    `json:"title"`
	Author        string    `json:"author"`
	Description   string    `json:"description"`
	Year          int16     `json:"year"`
	Language      string    `json:"language"`
	Publisher     string    `json:"publisher"`
	Pages         int16     `json:"pages"`
	CoverUrl      string    `json:"cover_url"`
	CreatedAt     time.Time `json:"created_at"`
	Categories    string    `json:"categories"`
	CommentCount  int64     `json:"comment_count"`
	BookmarkCount int64     `json:"bookmark_count"`
	RateCount     int64     `json:"rate_count"`
	RateSum       int64     `json:"rate_sum"`
	Rate1         int64     `json:"rate_1"`
	Rate2         int64     `json:"rate_2"`
	Rate3         int64     `json:"rate_3"`
	Rate4         int64     `json:"rate_4"`
	Rate5         int64     `json:"rate_5"`
	Rate6         int64     `json:"rate_6"`
	Rate7         int64     `json:"rate_7"`
	Rate8         int64     `json:"rate_8"`
	Rate9         int64     `json:"rate_9"`
	Rate10        int64     `json:"rate_10"`
}

type Bookmark struct {
	ID        int32     `json:"id"`
	BookID    int32     `json:"book_id"`
	CreatedBy int32     `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
}

type BookmarkCount struct {
	BookID int32 `json:"book_id"`
	Count  int64 `json:"count"`
}

type Category struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type CategorySummary struct {
	BookID     int32  `json:"book_id"`
	Categories []byte `json:"categories"`
}

type Comment struct {
	ID        int32     `json:"id"`
	Content   string    `json:"content"`
	BookID    int32     `json:"book_id"`
	CreatedBy int32     `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
}

type CommentCount struct {
	BookID int32 `json:"book_id"`
	Count  int64 `json:"count"`
}

type CommentDetail struct {
	ID         int32     `json:"id"`
	Content    string    `json:"content"`
	BookID     int32     `json:"book_id"`
	UserID     int32     `json:"user_id"`
	CreatedAt  time.Time `json:"created_at"`
	Username   string    `json:"username"`
	AAvatarUrl string    `json:"a_avatar_url"`
	AIsAdmin   string    `json:"a_is_admin"`
}

type Rate struct {
	ID        int32     `json:"id"`
	BookID    int32     `json:"book_id"`
	CreatedBy int32     `json:"created_by"`
	RateValue int32     `json:"rate_value"`
	CreatedAt time.Time `json:"created_at"`
}

type RateCount struct {
	BookID  int32 `json:"book_id"`
	Count   int64 `json:"count"`
	RateSum int64 `json:"rate_sum"`
	Rate1   int64 `json:"rate_1"`
	Rate2   int64 `json:"rate_2"`
	Rate3   int64 `json:"rate_3"`
	Rate4   int64 `json:"rate_4"`
	Rate5   int64 `json:"rate_5"`
	Rate6   int64 `json:"rate_6"`
	Rate7   int64 `json:"rate_7"`
	Rate8   int64 `json:"rate_8"`
	Rate9   int64 `json:"rate_9"`
	Rate10  int64 `json:"rate_10"`
}
