---
- hosts: do
  become: true

  vars:
    server_name: api.mybooklist.ndtai.me
    expose_port: 8080
    db_name: my_book_list
    db_user: dev
    db_pw: 123

  pre_tasks:
    - name: update-apt-cache
      ansible.builtin.apt:
        update_cache: true

  roles:
    - role: nginx
      become: true
    - role: geerlingguy.certbot
      become: true
      vars:
        certbot_install_method: snap
        certbot_auto_renew: false
        certbot_create_if_missing: true
        certbot_create_method: standalone
        certbot_certs:
          - email: ndtai772@gmail.com
            domains:
              - "{{ server_name }}"
    - role: postgresql
      become: true
    - role: meilisearch
      become: true

